from entity.kunde import Kunde

kunden = [
    Kunde(
        id=1,
        nachname="Mock1",
        vorname="Mock1"
    ),
    Kunde(
        id=2,
        nachname="Mock2",
        vorname="Mock2"
    ),
    Kunde(
        id=3,
        nachname="Mock3",
        vorname="Mock3"
    ),
    Kunde(
        id=4,
        nachname="Mock4",
        vorname="Mock4"
    ),
    Kunde(
        id=5,
        nachname="Mock5",
        vorname="Mock5"
    ),
    Kunde(
        id=6,
        nachname="Mock6",
        vorname="Mock6"
    ),
    Kunde(
        id=7,
        nachname="Mock7",
        vorname="Mock7"
    ),
    Kunde(
        id=8,
        nachname="Mock8",
        vorname="Mock8"
    ),
    Kunde(
        id=9,
        nachname="Mock9",
        vorname="Mock9"
    ),
    Kunde(
        id=10,
        nachname="Mock10",
        vorname="Mock10"
    ),
]
